project_id = "tonxgsqzjppuaskjstvl"

[functions.pagou-webhook]
verify_jwt = false

[functions.pagou-public-key]
verify_jwt = true

[functions.pagou-create-subscription]
verify_jwt = true

[functions.pagou-create-pix]
verify_jwt = true

[functions.pagou-billing-state]
verify_jwt = true

[functions.pagou-execute-payout]
verify_jwt = true

