/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthMotoristaRouteImport } from './routes/auth/motorista'
import { Route as AuthAnuncianteRouteImport } from './routes/auth/anunciante'
import { Route as AuthAdminRouteImport } from './routes/auth/admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMotoristaRoute = AuthMotoristaRouteImport.update({
  id: '/auth/motorista',
  path: '/auth/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAnuncianteRoute = AuthAnuncianteRouteImport.update({
  id: '/auth/anunciante',
  path: '/auth/anunciante',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/anunciante': typeof AuthAnuncianteRoute
  '/auth/motorista': typeof AuthMotoristaRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/anunciante': typeof AuthAnuncianteRoute
  '/auth/motorista': typeof AuthMotoristaRoute
  '/auth': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/anunciante': typeof AuthAnuncianteRoute
  '/auth/motorista': typeof AuthMotoristaRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/admin'
    | '/auth/anunciante'
    | '/auth/motorista'
    | '/auth/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/admin' | '/auth/anunciante' | '/auth/motorista' | '/auth'
  id:
    | '__root__'
    | '/'
    | '/auth/admin'
    | '/auth/anunciante'
    | '/auth/motorista'
    | '/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthAdminRoute: typeof AuthAdminRoute
  AuthAnuncianteRoute: typeof AuthAnuncianteRoute
  AuthMotoristaRoute: typeof AuthMotoristaRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/motorista': {
      id: '/auth/motorista'
      path: '/auth/motorista'
      fullPath: '/auth/motorista'
      preLoaderRoute: typeof AuthMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/anunciante': {
      id: '/auth/anunciante'
      path: '/auth/anunciante'
      fullPath: '/auth/anunciante'
      preLoaderRoute: typeof AuthAnuncianteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthAdminRoute: AuthAdminRoute,
  AuthAnuncianteRoute: AuthAnuncianteRoute,
  AuthMotoristaRoute: AuthMotoristaRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
