/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MotoristasRouteImport } from './routes/motoristas'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthMotoristaRouteImport } from './routes/auth/motorista'
import { Route as AuthAnuncianteRouteImport } from './routes/auth/anunciante'
import { Route as AuthAdminRouteImport } from './routes/auth/admin'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedMotoristaRouteRouteImport } from './routes/_authenticated/motorista/route'
import { Route as AuthenticatedAnuncianteRouteRouteImport } from './routes/_authenticated/anunciante/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedMotoristaIndexRouteImport } from './routes/_authenticated/motorista/index'
import { Route as AuthenticatedAnuncianteIndexRouteImport } from './routes/_authenticated/anunciante/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedMotoristaVeiculosRouteImport } from './routes/_authenticated/motorista/veiculos'
import { Route as AuthenticatedMotoristaPerfilRouteImport } from './routes/_authenticated/motorista/perfil'
import { Route as AuthenticatedMotoristaGanhosRouteImport } from './routes/_authenticated/motorista/ganhos'
import { Route as AuthenticatedMotoristaCampanhasRouteImport } from './routes/_authenticated/motorista/campanhas'
import { Route as AuthenticatedMotoristaAuditoriaRouteImport } from './routes/_authenticated/motorista/auditoria'
import { Route as AuthenticatedAnunciantePerfilRouteImport } from './routes/_authenticated/anunciante/perfil'
import { Route as AuthenticatedAnuncianteFinanceiroRouteImport } from './routes/_authenticated/anunciante/financeiro'
import { Route as AuthenticatedAdminVeiculosRouteImport } from './routes/_authenticated/admin/veiculos'
import { Route as AuthenticatedAdminMotoristasRouteImport } from './routes/_authenticated/admin/motoristas'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin/financeiro'
import { Route as AuthenticatedAdminComprovacoesRouteImport } from './routes/_authenticated/admin/comprovacoes'
import { Route as AuthenticatedAdminCampanhasRouteImport } from './routes/_authenticated/admin/campanhas'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin/auditoria'
import { Route as AuthenticatedAdminAnunciantesRouteImport } from './routes/_authenticated/admin/anunciantes'
import { Route as AuthenticatedAdminCampanhasIdRouteImport } from './routes/_authenticated/admin/campanhas.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristasRoute = MotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMotoristaRoute = AuthMotoristaRouteImport.update({
  id: '/auth/motorista',
  path: '/auth/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAnuncianteRoute = AuthAnuncianteRouteImport.update({
  id: '/auth/anunciante',
  path: '/auth/anunciante',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotoristaRouteRoute =
  AuthenticatedMotoristaRouteRouteImport.update({
    id: '/motorista',
    path: '/motorista',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnuncianteRouteRoute =
  AuthenticatedAnuncianteRouteRouteImport.update({
    id: '/anunciante',
    path: '/anunciante',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotoristaIndexRoute =
  AuthenticatedMotoristaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMotoristaRouteRoute,
  } as any)
const AuthenticatedAnuncianteIndexRoute =
  AuthenticatedAnuncianteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAnuncianteRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedMotoristaVeiculosRoute =
  AuthenticatedMotoristaVeiculosRouteImport.update({
    id: '/veiculos',
    path: '/veiculos',
    getParentRoute: () => AuthenticatedMotoristaRouteRoute,
  } as any)
const AuthenticatedMotoristaPerfilRoute =
  AuthenticatedMotoristaPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedMotoristaRouteRoute,
  } as any)
const AuthenticatedMotoristaGanhosRoute =
  AuthenticatedMotoristaGanhosRouteImport.update({
    id: '/ganhos',
    path: '/ganhos',
    getParentRoute: () => AuthenticatedMotoristaRouteRoute,
  } as any)
const AuthenticatedMotoristaCampanhasRoute =
  AuthenticatedMotoristaCampanhasRouteImport.update({
    id: '/campanhas',
    path: '/campanhas',
    getParentRoute: () => AuthenticatedMotoristaRouteRoute,
  } as any)
const AuthenticatedMotoristaAuditoriaRoute =
  AuthenticatedMotoristaAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedMotoristaRouteRoute,
  } as any)
const AuthenticatedAnunciantePerfilRoute =
  AuthenticatedAnunciantePerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedAnuncianteRouteRoute,
  } as any)
const AuthenticatedAnuncianteFinanceiroRoute =
  AuthenticatedAnuncianteFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAnuncianteRouteRoute,
  } as any)
const AuthenticatedAdminVeiculosRoute =
  AuthenticatedAdminVeiculosRouteImport.update({
    id: '/veiculos',
    path: '/veiculos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMotoristasRoute =
  AuthenticatedAdminMotoristasRouteImport.update({
    id: '/motoristas',
    path: '/motoristas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminComprovacoesRoute =
  AuthenticatedAdminComprovacoesRouteImport.update({
    id: '/comprovacoes',
    path: '/comprovacoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCampanhasRoute =
  AuthenticatedAdminCampanhasRouteImport.update({
    id: '/campanhas',
    path: '/campanhas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnunciantesRoute =
  AuthenticatedAdminAnunciantesRouteImport.update({
    id: '/anunciantes',
    path: '/anunciantes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCampanhasIdRoute =
  AuthenticatedAdminCampanhasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCampanhasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/motoristas': typeof MotoristasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/anunciante': typeof AuthenticatedAnuncianteRouteRouteWithChildren
  '/motorista': typeof AuthenticatedMotoristaRouteRouteWithChildren
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/anunciante': typeof AuthAnuncianteRoute
  '/auth/motorista': typeof AuthMotoristaRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/anunciantes': typeof AuthenticatedAdminAnunciantesRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/campanhas': typeof AuthenticatedAdminCampanhasRouteWithChildren
  '/admin/comprovacoes': typeof AuthenticatedAdminComprovacoesRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/motoristas': typeof AuthenticatedAdminMotoristasRoute
  '/admin/veiculos': typeof AuthenticatedAdminVeiculosRoute
  '/anunciante/financeiro': typeof AuthenticatedAnuncianteFinanceiroRoute
  '/anunciante/perfil': typeof AuthenticatedAnunciantePerfilRoute
  '/motorista/auditoria': typeof AuthenticatedMotoristaAuditoriaRoute
  '/motorista/campanhas': typeof AuthenticatedMotoristaCampanhasRoute
  '/motorista/ganhos': typeof AuthenticatedMotoristaGanhosRoute
  '/motorista/perfil': typeof AuthenticatedMotoristaPerfilRoute
  '/motorista/veiculos': typeof AuthenticatedMotoristaVeiculosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/anunciante/': typeof AuthenticatedAnuncianteIndexRoute
  '/motorista/': typeof AuthenticatedMotoristaIndexRoute
  '/admin/campanhas/$id': typeof AuthenticatedAdminCampanhasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/motoristas': typeof MotoristasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/anunciante': typeof AuthAnuncianteRoute
  '/auth/motorista': typeof AuthMotoristaRoute
  '/auth': typeof AuthIndexRoute
  '/admin/anunciantes': typeof AuthenticatedAdminAnunciantesRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/campanhas': typeof AuthenticatedAdminCampanhasRouteWithChildren
  '/admin/comprovacoes': typeof AuthenticatedAdminComprovacoesRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/motoristas': typeof AuthenticatedAdminMotoristasRoute
  '/admin/veiculos': typeof AuthenticatedAdminVeiculosRoute
  '/anunciante/financeiro': typeof AuthenticatedAnuncianteFinanceiroRoute
  '/anunciante/perfil': typeof AuthenticatedAnunciantePerfilRoute
  '/motorista/auditoria': typeof AuthenticatedMotoristaAuditoriaRoute
  '/motorista/campanhas': typeof AuthenticatedMotoristaCampanhasRoute
  '/motorista/ganhos': typeof AuthenticatedMotoristaGanhosRoute
  '/motorista/perfil': typeof AuthenticatedMotoristaPerfilRoute
  '/motorista/veiculos': typeof AuthenticatedMotoristaVeiculosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/anunciante': typeof AuthenticatedAnuncianteIndexRoute
  '/motorista': typeof AuthenticatedMotoristaIndexRoute
  '/admin/campanhas/$id': typeof AuthenticatedAdminCampanhasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/motoristas': typeof MotoristasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/anunciante': typeof AuthenticatedAnuncianteRouteRouteWithChildren
  '/_authenticated/motorista': typeof AuthenticatedMotoristaRouteRouteWithChildren
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/anunciante': typeof AuthAnuncianteRoute
  '/auth/motorista': typeof AuthMotoristaRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/admin/anunciantes': typeof AuthenticatedAdminAnunciantesRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/campanhas': typeof AuthenticatedAdminCampanhasRouteWithChildren
  '/_authenticated/admin/comprovacoes': typeof AuthenticatedAdminComprovacoesRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/motoristas': typeof AuthenticatedAdminMotoristasRoute
  '/_authenticated/admin/veiculos': typeof AuthenticatedAdminVeiculosRoute
  '/_authenticated/anunciante/financeiro': typeof AuthenticatedAnuncianteFinanceiroRoute
  '/_authenticated/anunciante/perfil': typeof AuthenticatedAnunciantePerfilRoute
  '/_authenticated/motorista/auditoria': typeof AuthenticatedMotoristaAuditoriaRoute
  '/_authenticated/motorista/campanhas': typeof AuthenticatedMotoristaCampanhasRoute
  '/_authenticated/motorista/ganhos': typeof AuthenticatedMotoristaGanhosRoute
  '/_authenticated/motorista/perfil': typeof AuthenticatedMotoristaPerfilRoute
  '/_authenticated/motorista/veiculos': typeof AuthenticatedMotoristaVeiculosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/anunciante/': typeof AuthenticatedAnuncianteIndexRoute
  '/_authenticated/motorista/': typeof AuthenticatedMotoristaIndexRoute
  '/_authenticated/admin/campanhas/$id': typeof AuthenticatedAdminCampanhasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/motoristas'
    | '/privacidade'
    | '/termos'
    | '/admin'
    | '/anunciante'
    | '/motorista'
    | '/notificacoes'
    | '/auth/admin'
    | '/auth/anunciante'
    | '/auth/motorista'
    | '/auth/'
    | '/admin/anunciantes'
    | '/admin/auditoria'
    | '/admin/campanhas'
    | '/admin/comprovacoes'
    | '/admin/financeiro'
    | '/admin/motoristas'
    | '/admin/veiculos'
    | '/anunciante/financeiro'
    | '/anunciante/perfil'
    | '/motorista/auditoria'
    | '/motorista/campanhas'
    | '/motorista/ganhos'
    | '/motorista/perfil'
    | '/motorista/veiculos'
    | '/admin/'
    | '/anunciante/'
    | '/motorista/'
    | '/admin/campanhas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/motoristas'
    | '/privacidade'
    | '/termos'
    | '/notificacoes'
    | '/auth/admin'
    | '/auth/anunciante'
    | '/auth/motorista'
    | '/auth'
    | '/admin/anunciantes'
    | '/admin/auditoria'
    | '/admin/campanhas'
    | '/admin/comprovacoes'
    | '/admin/financeiro'
    | '/admin/motoristas'
    | '/admin/veiculos'
    | '/anunciante/financeiro'
    | '/anunciante/perfil'
    | '/motorista/auditoria'
    | '/motorista/campanhas'
    | '/motorista/ganhos'
    | '/motorista/perfil'
    | '/motorista/veiculos'
    | '/admin'
    | '/anunciante'
    | '/motorista'
    | '/admin/campanhas/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/motoristas'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/anunciante'
    | '/_authenticated/motorista'
    | '/_authenticated/notificacoes'
    | '/auth/admin'
    | '/auth/anunciante'
    | '/auth/motorista'
    | '/auth/'
    | '/_authenticated/admin/anunciantes'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/campanhas'
    | '/_authenticated/admin/comprovacoes'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/motoristas'
    | '/_authenticated/admin/veiculos'
    | '/_authenticated/anunciante/financeiro'
    | '/_authenticated/anunciante/perfil'
    | '/_authenticated/motorista/auditoria'
    | '/_authenticated/motorista/campanhas'
    | '/_authenticated/motorista/ganhos'
    | '/_authenticated/motorista/perfil'
    | '/_authenticated/motorista/veiculos'
    | '/_authenticated/admin/'
    | '/_authenticated/anunciante/'
    | '/_authenticated/motorista/'
    | '/_authenticated/admin/campanhas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MotoristasRoute: typeof MotoristasRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  AuthAdminRoute: typeof AuthAdminRoute
  AuthAnuncianteRoute: typeof AuthAnuncianteRoute
  AuthMotoristaRoute: typeof AuthMotoristaRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoristas': {
      id: '/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof MotoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/motorista': {
      id: '/auth/motorista'
      path: '/auth/motorista'
      fullPath: '/auth/motorista'
      preLoaderRoute: typeof AuthMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/anunciante': {
      id: '/auth/anunciante'
      path: '/auth/anunciante'
      fullPath: '/auth/anunciante'
      preLoaderRoute: typeof AuthAnuncianteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motorista': {
      id: '/_authenticated/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof AuthenticatedMotoristaRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anunciante': {
      id: '/_authenticated/anunciante'
      path: '/anunciante'
      fullPath: '/anunciante'
      preLoaderRoute: typeof AuthenticatedAnuncianteRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motorista/': {
      id: '/_authenticated/motorista/'
      path: '/'
      fullPath: '/motorista/'
      preLoaderRoute: typeof AuthenticatedMotoristaIndexRouteImport
      parentRoute: typeof AuthenticatedMotoristaRouteRoute
    }
    '/_authenticated/anunciante/': {
      id: '/_authenticated/anunciante/'
      path: '/'
      fullPath: '/anunciante/'
      preLoaderRoute: typeof AuthenticatedAnuncianteIndexRouteImport
      parentRoute: typeof AuthenticatedAnuncianteRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/motorista/veiculos': {
      id: '/_authenticated/motorista/veiculos'
      path: '/veiculos'
      fullPath: '/motorista/veiculos'
      preLoaderRoute: typeof AuthenticatedMotoristaVeiculosRouteImport
      parentRoute: typeof AuthenticatedMotoristaRouteRoute
    }
    '/_authenticated/motorista/perfil': {
      id: '/_authenticated/motorista/perfil'
      path: '/perfil'
      fullPath: '/motorista/perfil'
      preLoaderRoute: typeof AuthenticatedMotoristaPerfilRouteImport
      parentRoute: typeof AuthenticatedMotoristaRouteRoute
    }
    '/_authenticated/motorista/ganhos': {
      id: '/_authenticated/motorista/ganhos'
      path: '/ganhos'
      fullPath: '/motorista/ganhos'
      preLoaderRoute: typeof AuthenticatedMotoristaGanhosRouteImport
      parentRoute: typeof AuthenticatedMotoristaRouteRoute
    }
    '/_authenticated/motorista/campanhas': {
      id: '/_authenticated/motorista/campanhas'
      path: '/campanhas'
      fullPath: '/motorista/campanhas'
      preLoaderRoute: typeof AuthenticatedMotoristaCampanhasRouteImport
      parentRoute: typeof AuthenticatedMotoristaRouteRoute
    }
    '/_authenticated/motorista/auditoria': {
      id: '/_authenticated/motorista/auditoria'
      path: '/auditoria'
      fullPath: '/motorista/auditoria'
      preLoaderRoute: typeof AuthenticatedMotoristaAuditoriaRouteImport
      parentRoute: typeof AuthenticatedMotoristaRouteRoute
    }
    '/_authenticated/anunciante/perfil': {
      id: '/_authenticated/anunciante/perfil'
      path: '/perfil'
      fullPath: '/anunciante/perfil'
      preLoaderRoute: typeof AuthenticatedAnunciantePerfilRouteImport
      parentRoute: typeof AuthenticatedAnuncianteRouteRoute
    }
    '/_authenticated/anunciante/financeiro': {
      id: '/_authenticated/anunciante/financeiro'
      path: '/financeiro'
      fullPath: '/anunciante/financeiro'
      preLoaderRoute: typeof AuthenticatedAnuncianteFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAnuncianteRouteRoute
    }
    '/_authenticated/admin/veiculos': {
      id: '/_authenticated/admin/veiculos'
      path: '/veiculos'
      fullPath: '/admin/veiculos'
      preLoaderRoute: typeof AuthenticatedAdminVeiculosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/motoristas': {
      id: '/_authenticated/admin/motoristas'
      path: '/motoristas'
      fullPath: '/admin/motoristas'
      preLoaderRoute: typeof AuthenticatedAdminMotoristasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/comprovacoes': {
      id: '/_authenticated/admin/comprovacoes'
      path: '/comprovacoes'
      fullPath: '/admin/comprovacoes'
      preLoaderRoute: typeof AuthenticatedAdminComprovacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/campanhas': {
      id: '/_authenticated/admin/campanhas'
      path: '/campanhas'
      fullPath: '/admin/campanhas'
      preLoaderRoute: typeof AuthenticatedAdminCampanhasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/anunciantes': {
      id: '/_authenticated/admin/anunciantes'
      path: '/anunciantes'
      fullPath: '/admin/anunciantes'
      preLoaderRoute: typeof AuthenticatedAdminAnunciantesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/campanhas/$id': {
      id: '/_authenticated/admin/campanhas/$id'
      path: '/$id'
      fullPath: '/admin/campanhas/$id'
      preLoaderRoute: typeof AuthenticatedAdminCampanhasIdRouteImport
      parentRoute: typeof AuthenticatedAdminCampanhasRoute
    }
  }
}

interface AuthenticatedAdminCampanhasRouteChildren {
  AuthenticatedAdminCampanhasIdRoute: typeof AuthenticatedAdminCampanhasIdRoute
}

const AuthenticatedAdminCampanhasRouteChildren: AuthenticatedAdminCampanhasRouteChildren =
  {
    AuthenticatedAdminCampanhasIdRoute: AuthenticatedAdminCampanhasIdRoute,
  }

const AuthenticatedAdminCampanhasRouteWithChildren =
  AuthenticatedAdminCampanhasRoute._addFileChildren(
    AuthenticatedAdminCampanhasRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnunciantesRoute: typeof AuthenticatedAdminAnunciantesRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminCampanhasRoute: typeof AuthenticatedAdminCampanhasRouteWithChildren
  AuthenticatedAdminComprovacoesRoute: typeof AuthenticatedAdminComprovacoesRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminMotoristasRoute: typeof AuthenticatedAdminMotoristasRoute
  AuthenticatedAdminVeiculosRoute: typeof AuthenticatedAdminVeiculosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnunciantesRoute: AuthenticatedAdminAnunciantesRoute,
    AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
    AuthenticatedAdminCampanhasRoute:
      AuthenticatedAdminCampanhasRouteWithChildren,
    AuthenticatedAdminComprovacoesRoute: AuthenticatedAdminComprovacoesRoute,
    AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
    AuthenticatedAdminMotoristasRoute: AuthenticatedAdminMotoristasRoute,
    AuthenticatedAdminVeiculosRoute: AuthenticatedAdminVeiculosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAnuncianteRouteRouteChildren {
  AuthenticatedAnuncianteFinanceiroRoute: typeof AuthenticatedAnuncianteFinanceiroRoute
  AuthenticatedAnunciantePerfilRoute: typeof AuthenticatedAnunciantePerfilRoute
  AuthenticatedAnuncianteIndexRoute: typeof AuthenticatedAnuncianteIndexRoute
}

const AuthenticatedAnuncianteRouteRouteChildren: AuthenticatedAnuncianteRouteRouteChildren =
  {
    AuthenticatedAnuncianteFinanceiroRoute:
      AuthenticatedAnuncianteFinanceiroRoute,
    AuthenticatedAnunciantePerfilRoute: AuthenticatedAnunciantePerfilRoute,
    AuthenticatedAnuncianteIndexRoute: AuthenticatedAnuncianteIndexRoute,
  }

const AuthenticatedAnuncianteRouteRouteWithChildren =
  AuthenticatedAnuncianteRouteRoute._addFileChildren(
    AuthenticatedAnuncianteRouteRouteChildren,
  )

interface AuthenticatedMotoristaRouteRouteChildren {
  AuthenticatedMotoristaAuditoriaRoute: typeof AuthenticatedMotoristaAuditoriaRoute
  AuthenticatedMotoristaCampanhasRoute: typeof AuthenticatedMotoristaCampanhasRoute
  AuthenticatedMotoristaGanhosRoute: typeof AuthenticatedMotoristaGanhosRoute
  AuthenticatedMotoristaPerfilRoute: typeof AuthenticatedMotoristaPerfilRoute
  AuthenticatedMotoristaVeiculosRoute: typeof AuthenticatedMotoristaVeiculosRoute
  AuthenticatedMotoristaIndexRoute: typeof AuthenticatedMotoristaIndexRoute
}

const AuthenticatedMotoristaRouteRouteChildren: AuthenticatedMotoristaRouteRouteChildren =
  {
    AuthenticatedMotoristaAuditoriaRoute: AuthenticatedMotoristaAuditoriaRoute,
    AuthenticatedMotoristaCampanhasRoute: AuthenticatedMotoristaCampanhasRoute,
    AuthenticatedMotoristaGanhosRoute: AuthenticatedMotoristaGanhosRoute,
    AuthenticatedMotoristaPerfilRoute: AuthenticatedMotoristaPerfilRoute,
    AuthenticatedMotoristaVeiculosRoute: AuthenticatedMotoristaVeiculosRoute,
    AuthenticatedMotoristaIndexRoute: AuthenticatedMotoristaIndexRoute,
  }

const AuthenticatedMotoristaRouteRouteWithChildren =
  AuthenticatedMotoristaRouteRoute._addFileChildren(
    AuthenticatedMotoristaRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAnuncianteRouteRoute: typeof AuthenticatedAnuncianteRouteRouteWithChildren
  AuthenticatedMotoristaRouteRoute: typeof AuthenticatedMotoristaRouteRouteWithChildren
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAnuncianteRouteRoute:
    AuthenticatedAnuncianteRouteRouteWithChildren,
  AuthenticatedMotoristaRouteRoute:
    AuthenticatedMotoristaRouteRouteWithChildren,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MotoristasRoute: MotoristasRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  AuthAdminRoute: AuthAdminRoute,
  AuthAnuncianteRoute: AuthAnuncianteRoute,
  AuthMotoristaRoute: AuthMotoristaRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
